# Generated by Django 5.1.6 on 2025-02-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('instrument', models.CharField(max_length=100)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_days', models.CharField(max_length=255)),
                ('available_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='section_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('max_students', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
        ),
    ]
