# Generated by Django 5.1.6 on 2025-02-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_musicsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicsection',
            name='max_students',
        ),
    ]
