# Generated by Django 5.0.4 on 2025-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_remove_musicsection_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
