# Generated by Django 5.0.4 on 2025-03-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_teacher_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
