# Generated by Django 5.0.4 on 2025-03-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_booking_payment_status_chatmessage'),
        ('Teacher', '0003_remove_musicsection_max_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Student.student'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_received_messages', to='Teacher.teacher'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='Student.student'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sent_messages', to='Teacher.teacher'),
        ),
    ]
