# Generated by Django 5.0.4 on 2025-03-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='teacher',
        ),
    ]
